import { render, screen} from '@testing-library/react';
import { PlayerComparisonStats } from './PlayerComparisonStats';
import { Player } from '../models';



describe('When given two `Player` props', () => {
    const goalie1: Player = {
        "clubTeam": null,
        "college": "Cornell",
        "collegeYear": 2021,
        "country": "Canada",
        "countryCode": "CAN",
        "dob": "1997-04-30",
        "age": 25,
        "firstName": "Jeff",
        "handedness": null,
        "height": "5'10",
        "highSchool": "The Hill Academy",
        "hometown": "Brampton, Ontario",
        "instagramUrl": "https://www.instagram.com/teater7/",
        "injuryDescription": null,
        "injuryStatus": "H",
        "isCaptain": false,
        "jerseyNum": 7,
        "lastName": "Teat",
        "lastNameSuffix": "",
        "nickname": null,
        "officialId": "001809",
        "bio": null,
        "position": "G",
        "positionName": "Goalie",
        "profileUrl": "https://img.premierlacrosseleague.com/Players/2022/jeff-teat.png",
        "scratch": false,
        "twitterUrl": "https://twitter.com/jteat15",
        "weight": 170,
        "expFromYear": 2021,
        "slug": "jeff-teat",
        "stats": {
            "GAA": 0,
            "assists": 16,
            "causedTurnovers": 1,
            "faceoffPct": 0,
            "faceoffs": 0,
            "faceoffsLost": 0,
            "faceoffsWon": 0,
            "foRecord": "0 - 0",
            "gamesPlayed": 10,
            "gamesStarted": 10,
            "goalieLosses": 0,
            "goalieTies": 0,
            "goalieWins": 0,
            "goals": 22,
            "goalsAgainst": 0,
            "groundBalls": 15,
            "numPenalties": 0,
            "onePointGoals": 22,
            "pim": 0,
            "pimValue": 0,
            "plusMinus": 0,
            "points": 38,
            "powerPlayGoals": 2,
            "powerPlayGoalsAgainst": 0,
            "powerPlayShots": 3,
            "saa": 0,
            "savePct": 0,
            "saves": 0,
            "scoresAgainst": 0,
            "shortHandedGoals": 0,
            "shortHandedGoalsAgainst": 0,
            "shortHandedShots": 0,
            "shotPct": 0.4230769230769231,
            "shots": 52,
            "shotsOnGoal": 36,
            "shotsOnGoalPct": 0.6923076923076923,
            "tof": 0,
            "turnovers": 21,
            "twoPointGoals": 0,
            "twoPointGoalsAgainst": 0,
            "twoPointShots": 0,
            "twoPointShotPct": 0,
            "twoPointShotsOnGoal": 0,
            "twoPointShotsOnGoalPct": 0,
            "twoPtGaa": 0
        }
    }

    const goalie2: Player = {
        "clubTeam": null,
        "college": "Albany",
        "collegeYear": 2015,
        "country": "United States",
        "countryCode": "IRQ",
        "dob": "1992-09-09",
        "age": 30,
        "firstName": "Lyle",
        "handedness": "R",
        "height": "6'0",
        "highSchool": "LaFayette",
        "hometown": "Onondaga Nation, NY",
        "instagramUrl": "https://www.instagram.com/lyle4thompson/",
        "injuryDescription": null,
        "injuryStatus": "H",
        "isCaptain": true,
        "jerseyNum": 4,
        "lastName": "Thompson",
        "lastNameSuffix": "",
        "nickname": null,
        "officialId": "000886",
        "bio": "Two-time Tewaaraton Award winner Lyle Thompson is one of the greatest players of all-time. He scored 400 points while at the University of Albany – the most in NCAA DI history.",
        "position": "G",
        "positionName": "Goalie",
        "profileUrl": "https://img.premierlacrosseleague.com/Players/2022/lyle-thompson.png",
        "scratch": false,
        "twitterUrl": "https://twitter.com/lyle4thompson",
        "weight": 180,
        "expFromYear": 2015,
        "slug": "lyle-thompson",
        "stats": {
          "GAA": 0,
          "assists": 18,
          "causedTurnovers": 5,
          "faceoffPct": 0,
          "faceoffs": 0,
          "faceoffsLost": 0,
          "faceoffsWon": 0,
          "foRecord": "0 - 0",
          "gamesPlayed": 9,
          "gamesStarted": 9,
          "goalieLosses": 0,
          "goalieTies": 0,
          "goalieWins": 0,
          "goals": 26,
          "goalsAgainst": 0,
          "groundBalls": 22,
          "numPenalties": 1,
          "onePointGoals": 26,
          "pim": 0.5,
          "pimValue": 0.5,
          "plusMinus": 0,
          "points": 44,
          "powerPlayGoals": 1,
          "powerPlayGoalsAgainst": 0,
          "powerPlayShots": 5,
          "saa": 0,
          "savePct": 0,
          "saves": 0,
          "scoresAgainst": 0,
          "shortHandedGoals": 0,
          "shortHandedGoalsAgainst": 0,
          "shortHandedShots": 0,
          "shotPct": 0.3939393939393939,
          "shots": 66,
          "shotsOnGoal": 42,
          "shotsOnGoalPct": 0.6363636363636364,
          "tof": 0,
          "turnovers": 25,
          "twoPointGoals": 0,
          "twoPointGoalsAgainst": 0,
          "twoPointShots": 0,
          "twoPointShotPct": 0,
          "twoPointShotsOnGoal": 0,
          "twoPointShotsOnGoalPct": 0,
          "twoPtGaa": 0
        }
    }

    it('should be able to set the selected `statFilter`', () => {
        render (<PlayerComparisonStats first={goalie1} second={goalie2} />);
        expect(
            screen.getByTestId('selectedStat').textContent
        ).toBe('Goalie Stats')
    })
})